services:

  data:
    image: pokequery-data
    container_name: data
    profiles: [setup]
    build:
      context: docker/poke-data
      dockerfile: Dockerfile
    volumes:
      - poke-data:/poke-data

  redis-stack:
    image: redis/redis-stack:7.2.0-v18
    container_name: redis-stack
    profiles: [all, backend, redis]
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
    - poke-redis:/data

  mongo:
    image: mongo
    container_name: mongo
    profiles: [all, backend, mongo]
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - poke-mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    profiles: [all, backend, mongo]
    depends_on:
      - mongo
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false


  frontend:
    image: pokequery-frontend
    container_name: frontend
    profiles: [all, frontend]
    depends_on:
      - redis-stack
      - loader
    build:
      context: src/frontend/poke-query
      dockerfile: Dockerfile 
    ports:
      - "3000:80"
    environment:
      API_BASE_URI: http://api:5112

  loader:
    image: pokequery-loader
    container_name: poke-loader
    profiles: [all, backend, loader]
    depends_on:
        - redis-stack
        - mongo
    build:
        context: src/backend/PokeLoader
        dockerfile: Dockerfile
    volumes:
        - poke-data:/poke-data
    environment:
      CACHE_DIRECTORY: /poke-data
      REDIS_CONNECTION: redis-stack
      MONGO_CONNECTION: mongodb://root:example@mongo:27017/

  api:
    image: pokequery-api
    container_name: api
    profiles: [all, backend, api]
    depends_on:
      - redis-stack
    build:
      context: src/backend/PokeQuery
      dockerfile: Dockerfile
    ports:
      - "5112:80"
    environment:
      REDIS_CONNECTION: redis-stack
      MONGO_CONNECTION: mongodb://root:example@mongo:27017/

volumes:
  poke-data:
    driver: local
  poke-redis:
    driver: local
  poke-mongo:
    driver: local