services:

  data:
    image: pokequery-data
    container_name: data
    profiles: [setup]
    build:
      context: docker/poke-data
      dockerfile: Dockerfile
    volumes:
      - poke-data:/poke-data

  redis-stack:
    image: redis/redis-stack:7.2.0-v18
    container_name: redis-stack
    profiles: [all, backend, redis]
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
    - poke-redis:/data


  frontend:
    image: pokequery-frontend
    container_name: frontend
    profiles: [all, frontend]
    depends_on:
      - redis-stack
      - loader
    build:
      context: src/frontend/poke-query
      dockerfile: Dockerfile 
    ports:
      - "3000:80"
    environment:
      API_BASE_URI: http://api:5112

  loader:
    image: pokequery-loader
    container_name: poke-loader
    profiles: [all, backend, loader]
    depends_on:
        - redis-stack
    build:
        context: src/backend/PokeLoader
        dockerfile: Dockerfile
    volumes:
        - poke-data:/poke-data
    environment:
      CACHE_DIRECTORY: /poke-data
      REDIS_CONNECTION: redis-stack

  api:
    image: pokequery-api
    container_name: api
    profiles: [all, backend, api]
    depends_on:
      - redis-stack
    build:
      context: src/backend/PokeQuery
      dockerfile: Dockerfile
    ports:
      - "5112:80"
    environment:
      REDIS_CONNECTION: redis-stack

volumes:
  poke-data:
    driver: local
  poke-redis:
    driver: local