version: '3.8'

services:

  frontend:
    image: pokequery-frontend
    container_name: frontend
    build:
      context: src/frontend/poke-query
      dockerfile: Dockerfile 
    ports:
      - "3000:80"
    environment:
      API_BASE_URI: http://localhost:5244

volumes:
  poke-data:
    driver: local